
server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&amp;
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.hkycu.goods.model
resources: # 指定静态资源的路径
  static-locations: classpath:/static/img
  cache-period: 0
